/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.awt.CardLayout;
import java.awt.Color;

/**
 *
 * @author Dario
 */
public class TelaPrincipal extends javax.swing.JFrame {
    
    
    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
        Rpainel1.setVisible(false);
        Rpainel2.setVisible(false);
        Rpainel3.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToggleButton1 = new javax.swing.JToggleButton();
        jToggleButton2 = new javax.swing.JToggleButton();
        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        pnpImc = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txt11 = new javax.swing.JLabel();
        txt18 = new javax.swing.JLabel();
        txt17 = new javax.swing.JLabel();
        txt16 = new javax.swing.JLabel();
        txt15 = new javax.swing.JLabel();
        txt14 = new javax.swing.JLabel();
        txt13 = new javax.swing.JLabel();
        txt12 = new javax.swing.JLabel();
        txt21 = new javax.swing.JLabel();
        txt22 = new javax.swing.JLabel();
        txt24 = new javax.swing.JLabel();
        txt25 = new javax.swing.JLabel();
        txt26 = new javax.swing.JLabel();
        txt27 = new javax.swing.JLabel();
        txt28 = new javax.swing.JLabel();
        txt23 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtAltura = new javax.swing.JTextField();
        txtPeso = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btnCalc = new javax.swing.JButton();
        txtseta1 = new javax.swing.JLabel();
        txtseta2 = new javax.swing.JLabel();
        txtseta3 = new javax.swing.JLabel();
        txtseta4 = new javax.swing.JLabel();
        txtseta5 = new javax.swing.JLabel();
        txtseta6 = new javax.swing.JLabel();
        txtseta7 = new javax.swing.JLabel();
        txtseta8 = new javax.swing.JLabel();
        txtRes = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtnunr = new javax.swing.JSpinner();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        pnpHistorico = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        Rpainel1 = new javax.swing.JPanel();
        lblR1 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txtimcr1 = new javax.swing.JLabel();
        txttipor1 = new javax.swing.JLabel();
        Rpainel2 = new javax.swing.JPanel();
        lblR2 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        txtimcr2 = new javax.swing.JLabel();
        txttipor2 = new javax.swing.JLabel();
        Rpainel3 = new javax.swing.JPanel();
        lblR3 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        txtimcr3 = new javax.swing.JLabel();
        txttipor3 = new javax.swing.JLabel();
        pnpInfo = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();

        jToggleButton1.setText("jToggleButton1");

        jToggleButton2.setText("jToggleButton2");

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Calculadora IMC");
        setResizable(false);

        jPanel1.setLayout(new java.awt.CardLayout());

        pnpImc.setBackground(new java.awt.Color(153, 153, 153));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("IMC");

        txt11.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt11.setText("Magreza grave");

        txt18.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt18.setText("Obesidade Grau III");

        txt17.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt17.setText("Obesidade Grau II");

        txt16.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt16.setText("Obesidade Grau I");

        txt15.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt15.setText("Sobrepeso");

        txt14.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt14.setText("Saudável");

        txt13.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt13.setText("Magreza leve");

        txt12.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt12.setText("Magreza moderada");

        txt21.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt21.setText(" ≤15.9");

        txt22.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt22.setText("16.0 - 16.9");

        txt24.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt24.setText("18.5 - 24.9");

        txt25.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt25.setText("25.0 - 29.9");

        txt26.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt26.setText("30.0 - 34.9");

        txt27.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt27.setText("35.0 - 39.9");

        txt28.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt28.setText("≥40.0");

        txt23.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt23.setText("17.0 - 18.4");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel3.setText("Altura");

        txtAltura.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txtPeso.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Peso");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 204, 51));
        jLabel5.setText("cm");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 204, 102));
        jLabel6.setText("Kg");

        jLabel7.setForeground(new java.awt.Color(0, 153, 51));
        jLabel7.setText("-----------------");

        jLabel8.setForeground(new java.awt.Color(0, 153, 51));
        jLabel8.setText("-----------------");

        btnCalc.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnCalc.setText("Calcular");
        btnCalc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcActionPerformed(evt);
            }
        });

        txtseta1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        txtseta2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        txtseta3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        txtseta4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        txtseta5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        txtseta6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        txtseta7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        txtseta8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        txtRes.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtRes.setText("0.0");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("Imc:");

        txtNome.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel13.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel13.setText("Nome");

        txtnunr.setModel(new javax.swing.SpinnerNumberModel(1, 1, 3, 1));

        jLabel14.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel14.setText("Guardar");

        jLabel15.setText("Espaço:");

        javax.swing.GroupLayout pnpImcLayout = new javax.swing.GroupLayout(pnpImc);
        pnpImc.setLayout(pnpImcLayout);
        pnpImcLayout.setHorizontalGroup(
            pnpImcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnpImcLayout.createSequentialGroup()
                .addGroup(pnpImcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnpImcLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(pnpImcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnpImcLayout.createSequentialGroup()
                                .addGroup(pnpImcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtseta1, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtseta2, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtseta3, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtseta4, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtseta5, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtseta6, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtseta7, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtseta8, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pnpImcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txt12, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt13, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt14, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt15, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt16, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt17, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt18, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt11, javax.swing.GroupLayout.Alignment.LEADING)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnpImcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(pnpImcLayout.createSequentialGroup()
                                    .addGap(10, 10, 10)
                                    .addComponent(jLabel14)))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnpImcLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pnpImcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnpImcLayout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addGap(18, 18, 18))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnpImcLayout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtnunr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20)))))
                .addGroup(pnpImcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnpImcLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 147, Short.MAX_VALUE)
                        .addGroup(pnpImcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt27)
                            .addComponent(txt21)
                            .addComponent(txt22)
                            .addComponent(txt23)
                            .addComponent(txt24)
                            .addComponent(txt25)
                            .addComponent(txt26)
                            .addComponent(txt28))
                        .addGap(65, 65, 65))
                    .addGroup(pnpImcLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(pnpImcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnpImcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(pnpImcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel1)
                                    .addGroup(pnpImcLayout.createSequentialGroup()
                                        .addComponent(txtPeso, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel6))
                                    .addGroup(pnpImcLayout.createSequentialGroup()
                                        .addComponent(txtAltura, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel5))
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnpImcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnpImcLayout.createSequentialGroup()
                                    .addGap(12, 12, 12)
                                    .addComponent(jLabel10)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtRes))
                                .addComponent(btnCalc)))
                        .addContainerGap(172, Short.MAX_VALUE))))
        );
        pnpImcLayout.setVerticalGroup(
            pnpImcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnpImcLayout.createSequentialGroup()
                .addGroup(pnpImcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnpImcLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnpImcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel13))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnpImcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtAltura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addGroup(pnpImcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnpImcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPeso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(txtnunr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnCalc)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                        .addGroup(pnpImcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtRes)
                            .addComponent(jLabel10))
                        .addGap(166, 166, 166)
                        .addComponent(txtseta8, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnpImcLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(pnpImcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(pnpImcLayout.createSequentialGroup()
                                .addGroup(pnpImcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(pnpImcLayout.createSequentialGroup()
                                        .addGroup(pnpImcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(pnpImcLayout.createSequentialGroup()
                                                .addGroup(pnpImcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addGroup(pnpImcLayout.createSequentialGroup()
                                                        .addGroup(pnpImcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                            .addGroup(pnpImcLayout.createSequentialGroup()
                                                                .addGroup(pnpImcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                                    .addGroup(pnpImcLayout.createSequentialGroup()
                                                                        .addGroup(pnpImcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                            .addComponent(txtseta1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                            .addGroup(pnpImcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                .addComponent(txt11)
                                                                                .addComponent(txt21)))
                                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                        .addGroup(pnpImcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                                            .addComponent(txt12)
                                                                            .addComponent(txt22)))
                                                                    .addComponent(txtseta2, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addGroup(pnpImcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                                    .addComponent(txt13)
                                                                    .addComponent(txt23)))
                                                            .addComponent(txtseta3, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addGroup(pnpImcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                            .addComponent(txt14)
                                                            .addComponent(txt24)))
                                                    .addComponent(txtseta4, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(pnpImcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                    .addComponent(txt15)
                                                    .addComponent(txt25)))
                                            .addComponent(txtseta5, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(pnpImcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(txt16)
                                            .addComponent(txt26)))
                                    .addComponent(txtseta6, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pnpImcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txt17)
                                    .addComponent(txt27)))
                            .addComponent(txtseta7, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnpImcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt18)
                            .addComponent(txt28))))
                .addContainerGap())
        );

        jPanel1.add(pnpImc, "tela1");

        pnpHistorico.setBackground(new java.awt.Color(153, 153, 153));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel2.setText("Resultados");

        Rpainel1.setBackground(new java.awt.Color(102, 102, 102));

        lblR1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblR1.setText("...");

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel16.setText("IMC:");

        txtimcr1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtimcr1.setText("...");

        txttipor1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txttipor1.setText("...");

        javax.swing.GroupLayout Rpainel1Layout = new javax.swing.GroupLayout(Rpainel1);
        Rpainel1.setLayout(Rpainel1Layout);
        Rpainel1Layout.setHorizontalGroup(
            Rpainel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Rpainel1Layout.createSequentialGroup()
                .addGap(156, 156, 156)
                .addGroup(Rpainel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblR1)
                    .addGroup(Rpainel1Layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtimcr1)))
                .addGap(18, 18, 18)
                .addComponent(txttipor1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Rpainel1Layout.setVerticalGroup(
            Rpainel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Rpainel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblR1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Rpainel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(txtimcr1)
                    .addComponent(txttipor1))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        Rpainel2.setBackground(new java.awt.Color(102, 102, 102));

        lblR2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblR2.setText("...");

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel17.setText("IMC:");

        txtimcr2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtimcr2.setText("...");

        txttipor2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txttipor2.setText("...");

        javax.swing.GroupLayout Rpainel2Layout = new javax.swing.GroupLayout(Rpainel2);
        Rpainel2.setLayout(Rpainel2Layout);
        Rpainel2Layout.setHorizontalGroup(
            Rpainel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Rpainel2Layout.createSequentialGroup()
                .addGap(155, 155, 155)
                .addGroup(Rpainel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblR2)
                    .addGroup(Rpainel2Layout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtimcr2)))
                .addGap(18, 18, 18)
                .addComponent(txttipor2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Rpainel2Layout.setVerticalGroup(
            Rpainel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Rpainel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblR2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Rpainel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(txtimcr2)
                    .addComponent(txttipor2))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        Rpainel3.setBackground(new java.awt.Color(102, 102, 102));

        lblR3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblR3.setText("...");

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel18.setText("IMC:");

        txtimcr3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtimcr3.setText("...");

        txttipor3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txttipor3.setText("...");

        javax.swing.GroupLayout Rpainel3Layout = new javax.swing.GroupLayout(Rpainel3);
        Rpainel3.setLayout(Rpainel3Layout);
        Rpainel3Layout.setHorizontalGroup(
            Rpainel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Rpainel3Layout.createSequentialGroup()
                .addGap(155, 155, 155)
                .addGroup(Rpainel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(Rpainel3Layout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtimcr3))
                    .addComponent(lblR3))
                .addGap(18, 18, 18)
                .addComponent(txttipor3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Rpainel3Layout.setVerticalGroup(
            Rpainel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Rpainel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblR3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Rpainel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(txtimcr3)
                    .addComponent(txttipor3))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnpHistoricoLayout = new javax.swing.GroupLayout(pnpHistorico);
        pnpHistorico.setLayout(pnpHistoricoLayout);
        pnpHistoricoLayout.setHorizontalGroup(
            pnpHistoricoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnpHistoricoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnpHistoricoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Rpainel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Rpainel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Rpainel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(pnpHistoricoLayout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addComponent(jLabel2)
                .addContainerGap(150, Short.MAX_VALUE))
        );
        pnpHistoricoLayout.setVerticalGroup(
            pnpHistoricoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnpHistoricoLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel2)
                .addGap(39, 39, 39)
                .addComponent(Rpainel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Rpainel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Rpainel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        jPanel1.add(pnpHistorico, "tela2");

        pnpInfo.setBackground(new java.awt.Color(153, 153, 153));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel9.setText("Imformações");

        jLabel11.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel11.setText("<html>O Índice de Massa Corporal, conhecido pela sigla IMC, é um cálculo simples que permite medir se alguém está ou não com o peso ideal. Ele aponta se o peso está adequado ou se está abaixo ou acima do peso.</html>");

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/information-outline.png"))); // NOI18N

        javax.swing.GroupLayout pnpInfoLayout = new javax.swing.GroupLayout(pnpInfo);
        pnpInfo.setLayout(pnpInfoLayout);
        pnpInfoLayout.setHorizontalGroup(
            pnpInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnpInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnpInfoLayout.createSequentialGroup()
                .addContainerGap(156, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addGap(153, 153, 153))
        );
        pnpInfoLayout.setVerticalGroup(
            pnpInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnpInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addGap(29, 29, 29)
                .addGroup(pnpInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(238, Short.MAX_VALUE))
        );

        jPanel1.add(pnpInfo, "tela3");

        jMenuBar1.setBackground(new java.awt.Color(153, 153, 153));

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/format-list-bulleted-square.png"))); // NOI18N
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/chart-box-plus-outline.png"))); // NOI18N
        jMenuItem1.setText("IMC");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/history.png"))); // NOI18N
        jMenuItem2.setText("Resultados");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/information-outline.png"))); // NOI18N
        jMenuItem3.setText("Info");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_jMenu1ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
         CardLayout cl = (CardLayout) jPanel1.getLayout();
        cl.show(jPanel1, "tela1");
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        CardLayout cl = (CardLayout) jPanel1.getLayout();
        cl.show(jPanel1, "tela2");
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void btnCalcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcActionPerformed
        // TODO add your handling code here:
        float A = Float.parseFloat(txtAltura.getText());
        float P = Float.parseFloat(txtPeso.getText());
        String RA = null;
        int nunr = Integer.parseInt(txtnunr.getValue().toString());
        double imc; 
        imc = P / (A*A); 
            txtseta1.setForeground(Color.black);
            txt11.setForeground(Color.black);
            txt21.setForeground(Color.black);
            txtRes.setForeground(Color.black);
            txt12.setForeground(Color.black);
            txt22.setForeground(Color.black);
            txt13.setForeground(Color.black);
            txt23.setForeground(Color.black);
            txt14.setForeground(Color.black);
            txt24.setForeground(Color.black);
            txt15.setForeground(Color.black);
            txt25.setForeground(Color.black);
            txt16.setForeground(Color.black);
            txt26.setForeground(Color.black);
            txt17.setForeground(Color.black);
            txt27.setForeground(Color.black);
            txt18.setForeground(Color.black);
            txt28.setForeground(Color.black);
            txtseta1.setText("");
            txtseta2.setText("");
            txtseta3.setText("");
            txtseta4.setText("");
            txtseta5.setText("");
            txtseta6.setText("");
            txtseta7.setText("");
            txtseta8.setText("");
        if (imc < 16){
            txtseta1.setText("<html><strong> > </strong></html>");
            txtseta1.setForeground(Color.blue);
            txt11.setForeground(Color.blue);
            txt21.setForeground(Color.blue);
            txtRes.setForeground(Color.blue);
            RA = "Magreza grave";
        } else if((imc >= 16.0)&&(imc < 17)){
            txtseta2.setText("<html><strong> > </strong></html>");
            txtseta2.setForeground(Color.blue);
            txt12.setForeground(Color.blue);
            txt22.setForeground(Color.blue);
            txtRes.setForeground(Color.blue);
            RA = "Magreza moderada";
        } else if ((imc >= 17.0)&&(imc < 18.5)){
            txtseta3.setText("<html><strong> > </strong></html>");
            txtseta3.setForeground(Color.blue);
            txt13.setForeground(Color.blue);
            txt23.setForeground(Color.blue);
            txtRes.setForeground(Color.blue);
            RA = "Magreza leve";
        } else if ((imc >= 18.5)&&(imc < 25)){
            txtseta4.setText("<html><strong> > </strong></html>");
            txtseta4.setForeground(Color.green);
            txt14.setForeground(Color.green);
            txt24.setForeground(Color.green);
            txtRes.setForeground(Color.green);
            RA = "Saudável";
        } else if ((imc >= 25.0)&&(imc < 30)){
            txtseta5.setText("<html><strong> > </strong></html>");
            txtseta5.setForeground(Color.orange);
            txt15.setForeground(Color.orange);
            txt25.setForeground(Color.orange);
            txtRes.setForeground(Color.orange);
            RA = "Sobrepeso";
        } else if ((imc >= 30.0)&&(imc < 35)){
            txtseta6.setText("<html><strong> > </strong></html>");
            txtseta6.setForeground(Color.red);
            txt16.setForeground(Color.red);
            txt26.setForeground(Color.red);
            txtRes.setForeground(Color.red);
            RA = "Obesidade Grau I";
        } else if ((imc >= 35.0)&&(imc < 40)){
            txtseta7.setText("<html><strong> > </strong></html>");
            txtseta7.setForeground(Color.red);
            txt17.setForeground(Color.red);
            txt27.setForeground(Color.red);
            txtRes.setForeground(Color.red);
            RA = "Obesidade Grau II";
        } else if (imc >= 40.0){
            txtseta8.setText("<html><strong> > </strong></html>");
            txtseta8.setForeground(Color.red);
            txt18.setForeground(Color.red);
            txt28.setForeground(Color.red);
            txtRes.setForeground(Color.red);
            RA = "Obesidade Grau III";
        } else {
            
        }
        txtRes.setText(String.format("%.1f", imc));
       
        String Rn = txtNome.getText();
        String RR = txtRes.getText();
        if (nunr == 1){
          lblR1.setText(Rn);
          txtimcr1.setText(RR);
          txttipor1.setText(RA);
          Rpainel1.setVisible(true);
        } else if (nunr == 2) {
          lblR2.setText(Rn);
          txtimcr2.setText(RR);
          txttipor2.setText(RA);
          Rpainel2.setVisible(true);  
        } else if (nunr == 3){
          lblR3.setText(Rn);
          txtimcr3.setText(RR);
          txttipor3.setText(RA);
          Rpainel3.setVisible(true);   
        } else {
            
        }
    }//GEN-LAST:event_btnCalcActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        CardLayout cl = (CardLayout) jPanel1.getLayout();
        cl.show(jPanel1, "tela3");
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Rpainel1;
    private javax.swing.JPanel Rpainel2;
    private javax.swing.JPanel Rpainel3;
    private javax.swing.JButton btnCalc;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JLabel lblR1;
    private javax.swing.JLabel lblR2;
    private javax.swing.JLabel lblR3;
    private javax.swing.JPanel pnpHistorico;
    private javax.swing.JPanel pnpImc;
    private javax.swing.JPanel pnpInfo;
    private javax.swing.JLabel txt11;
    private javax.swing.JLabel txt12;
    private javax.swing.JLabel txt13;
    private javax.swing.JLabel txt14;
    private javax.swing.JLabel txt15;
    private javax.swing.JLabel txt16;
    private javax.swing.JLabel txt17;
    private javax.swing.JLabel txt18;
    private javax.swing.JLabel txt21;
    private javax.swing.JLabel txt22;
    private javax.swing.JLabel txt23;
    private javax.swing.JLabel txt24;
    private javax.swing.JLabel txt25;
    private javax.swing.JLabel txt26;
    private javax.swing.JLabel txt27;
    private javax.swing.JLabel txt28;
    private javax.swing.JTextField txtAltura;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtPeso;
    private javax.swing.JLabel txtRes;
    private javax.swing.JLabel txtimcr1;
    private javax.swing.JLabel txtimcr2;
    private javax.swing.JLabel txtimcr3;
    private javax.swing.JSpinner txtnunr;
    private javax.swing.JLabel txtseta1;
    private javax.swing.JLabel txtseta2;
    private javax.swing.JLabel txtseta3;
    private javax.swing.JLabel txtseta4;
    private javax.swing.JLabel txtseta5;
    private javax.swing.JLabel txtseta6;
    private javax.swing.JLabel txtseta7;
    private javax.swing.JLabel txtseta8;
    private javax.swing.JLabel txttipor1;
    private javax.swing.JLabel txttipor2;
    private javax.swing.JLabel txttipor3;
    // End of variables declaration//GEN-END:variables
}
